version: '2'
services:
    web:
        build: .
        links:
            - redis
        ports:
            - "8080:8080"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
